pipeline {
  agent {
    docker { image 'cimg/openjdk:11.0' }
  }
  parameters {
    imageTag(name: 'DOCKER_IMAGE', image: 'thcathy/esl-rest', filter: '.*(2.0).*')
  }

  stages {
   stage("deploy and verify") {
      agent {
        docker {
          image 'ansible/ansible-runner'
        }
      }
      steps {
        ansiblePlaybook(
          inventory: 'ansible/inventory_prod2',
          limit: 'prod2',
          extras: "-e docker_image_tag=${DOCKER_IMAGE_TAG}",
          playbook: 'ansible/deploy.yml',
          credentialsId: 'Jenkins-master',
          vaultCredentialsId: 'ansible_vault_id',
        )
      }
    }
  }

}
