name: Build feature branches

on:
  push:
    branches:
      - '*'
      - '!master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APISERVER_HOST: ${{ secrets.APISERVER_HOST }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check assemble
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: 'build/test-results/test/*.xml'
