name: Manual deploy to k8s

on:
  workflow_dispatch:
    inputs:
      docker_tag_version:
        description: 'docker tag version. e.g. 2.0.0-7'
        default: latest
        required: true
      target_env:
        description: 'target environment'
        type: choice
        default: uat
        options:
        - uat
        - prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: deploy to k8s [${{ github.event.inputs.target_env }}]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v3
    - name: Run ansible playbook to deploy via k8s
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ansible/deploy-k8s.yml
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        vault_password: ${{ secrets.VAULT_PASSWORD }}
        options: |
          --inventory ansible/inventory_k8s-${{ github.event.inputs.target_env }}
          -e docker_image_tag=${{ github.event.inputs.docker_tag_version }}
          -e image_generation_server_host=${{ secrets.IMAGE_GENERATION_SERVER_HOST }}
          -e image_generation_server_apikey=${{ secrets.IMAGE_GENERATION_SERVER_APIKEY }}
          -e replicate_api_token=${{ secrets.REPLICATE_API_TOKEN }}
